[www]
user  = www-data
group = www-data

listen = 127.0.0.1:9000

; Dynamic — 25 workers × 45 MB = ~1125 MB max
pm                   = dynamic
pm.max_children      = 25
pm.start_servers     = 5
pm.min_spare_servers = 3
pm.max_spare_servers = 10
pm.max_requests      = 500

; Timeout
request_terminate_timeout = 60

; Logs
catch_workers_output       = yes
php_flag[display_errors]   = off
php_admin_value[error_log] = /dev/stderr
php_admin_flag[log_errors] = on

; Passer les variables d'env au processus PHP
clear_env = no
